// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6ItJSEfIKxAK98cyPCu_FUuEMbCUaLHQ',
    appId: '1:1009061742099:web:37451115d9b1a7316121e6',
    messagingSenderId: '1009061742099',
    projectId: 'fir-55785',
    authDomain: 'fir-55785.firebaseapp.com',
    storageBucket: 'fir-55785.firebasestorage.app',
    measurementId: 'G-ZRQG2CV2EC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCynp6m_Q1-lA-Dgf1rujPOIPeCphXcsQ',
    appId: '1:1009061742099:android:35cf57a28b0b70126121e6',
    messagingSenderId: '1009061742099',
    projectId: 'fir-55785',
    storageBucket: 'fir-55785.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOlNIZXy-MHjrBQTyGyEa-nKfP_TE8nUI',
    appId: '1:1009061742099:ios:e4f45e4b1992b1946121e6',
    messagingSenderId: '1009061742099',
    projectId: 'fir-55785',
    storageBucket: 'fir-55785.firebasestorage.app',
    iosBundleId: 'com.example.mynewapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOlNIZXy-MHjrBQTyGyEa-nKfP_TE8nUI',
    appId: '1:1009061742099:ios:e4f45e4b1992b1946121e6',
    messagingSenderId: '1009061742099',
    projectId: 'fir-55785',
    storageBucket: 'fir-55785.firebasestorage.app',
    iosBundleId: 'com.example.mynewapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6ItJSEfIKxAK98cyPCu_FUuEMbCUaLHQ',
    appId: '1:1009061742099:web:3eea79a33e56cac56121e6',
    messagingSenderId: '1009061742099',
    projectId: 'fir-55785',
    authDomain: 'fir-55785.firebaseapp.com',
    storageBucket: 'fir-55785.firebasestorage.app',
    measurementId: 'G-ESHQSMSHKE',
  );
}
